# Generated by Django 5.0.9 on 2025-11-08 22:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the waypoint', max_length=255)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('park', 'Park'), ('museum', 'Museum'), ('landmark', 'Landmark'), ('hotel', 'Hotel'), ('transit', 'Transit Station'), ('other', 'Other')], default='other', help_text='Category of the waypoint', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about this waypoint')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic coordinates (longitude, latitude)', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='waypoints_w_categor_f88d6c_idx'), models.Index(fields=['created_at'], name='waypoints_w_created_710fa2_idx')],
            },
        ),
    ]
