import type { Shelter, NewsItem } from "./types"

export const mockShelters: Shelter[] = [
  {
    id: "1",
    name: "Center of Hope",
    address: "1501 Imperial Ave, San Diego, CA 92101",
    lat: 32.7157,
    lng: -117.1611,
    phone: "(619) 123-4567",
    capacity: 50,
    availableBeds: 12,
    services: ["Food", "Shower", "Clothing", "Counseling"],
    hours: "24 hours",
    description: "Shelter with full services, meals three times a day",
  },
  {
    id: "2",
    name: "San José Shelter",
    address: "3350 E St, San Diego, CA 92102",
    lat: 32.7089,
    lng: -117.1289,
    phone: "(619) 234-5678",
    capacity: 30,
    availableBeds: 5,
    services: ["Food", "Shower", "Medical"],
    hours: "6:00 PM - 8:00 AM",
    description: "Night shelter with basic medical care",
  },
  {
    id: "3",
    name: "House of Peace",
    address: "2020 Newton Ave, San Diego, CA 92113",
    lat: 32.6981,
    lng: -117.1342,
    phone: "(619) 345-6789",
    capacity: 40,
    availableBeds: 18,
    services: ["Food", "Shower", "Clothing", "Social Work"],
    hours: "24 hours",
    description: "Family shelter with reintegration programs",
  },
  {
    id: "4",
    name: "New Life Shelter",
    address: "252 16th St, San Diego, CA 92101",
    lat: 32.7098,
    lng: -117.1489,
    phone: "(619) 456-7890",
    capacity: 25,
    availableBeds: 8,
    services: ["Food", "Shower", "Legal Counseling"],
    hours: "5:00 PM - 9:00 AM",
    description: "Shelter offering legal and documentation support",
  },
  {
    id: "5",
    name: "Good Samaritan Community Center",
    address: "1501 30th St, San Diego, CA 92102",
    lat: 32.7245,
    lng: -117.1298,
    phone: "(619) 567-8901",
    capacity: 60,
    availableBeds: 22,
    services: ["Food", "Shower", "Clothing", "Medical", "Dental"],
    hours: "24 hours",
    description: "Comprehensive center with medical and dental services",
  },
  {
    id: "6",
    name: "Northern Shelter",
    address: "4002 Fairmount Ave, San Diego, CA 92105",
    lat: 32.7456,
    lng: -117.1089,
    phone: "(619) 678-9012",
    capacity: 35,
    availableBeds: 15,
    services: ["Food", "Shower", "Clothing"],
    hours: "24 hours",
    description: "Community shelter with a family-friendly environment",
  },
]

export const mockNews: NewsItem[] = [
  {
    id: "1",
    title: "New Employment Program Available",
    date: "2025-01-15",
    category: "resource",
    content:
      "A new job training program has opened with immediate employment opportunities in construction and services.",
  },
  {
    id: "2",
    title: "Winter Clothing Distribution",
    date: "2025-01-14",
    category: "event",
    content: "This Saturday there will be a free coat and blanket distribution at the Center of Hope from 10 AM to 4 PM.",
  },
  {
    id: "3",
    title: "Alert: Low Temperatures This Week",
    date: "2025-01-13",
    category: "alert",
    content: "Below-freezing temperatures are expected. All shelters will extend hours and emergency capacity.",
  },
  {
    id: "4",
    title: "Free Dental Clinic",
    date: "2025-01-12",
    category: "resource",
    content: "Free dental services available at House of Peace every Tuesday from 9 AM to 3 PM.",
  },
]
