# Generated by Django 5.0.9 on 2025-11-10 03:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource/location', max_length=200)),
                ('rtype', models.CharField(choices=[('food', 'Food'), ('shelter', 'Shelter'), ('restroom', 'Restroom'), ('medical', 'Medical'), ('legal', 'Legal'), ('donation', 'Donation Location'), ('other', 'Other')], help_text='Category of service provided', max_length=20, verbose_name='Resource Type')),
                ('description', models.TextField(blank=True, help_text='Detailed description of services offered')),
                ('hours_json', models.JSONField(blank=True, default=dict, help_text='Weekly schedule in format: {"mon":[["09:00","17:00"]], "tue":...}')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=40)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Website URL')),
                ('address', models.CharField(blank=True, help_text='Street address', max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic location (point)', srid=4326)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Additional tags/keywords as a list')),
                ('state', models.CharField(choices=[('visible', 'Visible'), ('not_visible', 'Not Visible'), ('rejected', 'Rejected')], default='visible', help_text='Visibility and moderation state', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if state is rejected)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for time-limited resources', null=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Service provider who submitted this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rtype', 'state'], name='resources_r_rtype_972034_idx'), models.Index(fields=['state'], name='resources_r_state_756ff0_idx'), models.Index(fields=['provider'], name='resources_r_provide_a8cc72_idx')],
            },
        ),
    ]
